# Generated by Django 4.2.7 on 2023-11-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
