# Generated by Django 4.2.7 on 2023-11-21 05:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
